var dataTab1 = [
    {
        "src":"images/tab-1/于雪.jpg",
        "name":"于雪",
        "needtip":2
    },
    {
        "src":"images/tab-1/侯淑贞.jpg",
        "name":"侯淑贞",
        "needtip":2
    },
    {
        "src":"images/tab-1/关贻涛（开辰书）.jpg",
        "name":"关贻涛",
        "needtip":2
    },
    {
        "src":"images/tab-1/刘传好.jpg",
        "name":"刘传好",
        "needtip":2
    },
    {
        "src":"images/tab-1/刘建军.jpg",
        "name":"刘建军",
        "needtip":2
    },
    {
        "src":"images/tab-1/刘怀海.jpg",
        "name":"刘怀海",
        "needtip":2
    },
    {
        "src":"images/tab-1/刘柏汝.jpg",
        "name":"刘柏汝",
        "needtip":2
    },
    {
        "src":"images/tab-1/单虹.jpg",
        "name":"单虹",
        "needtip":2
    },
    {
        "src":"images/tab-1/吕琨鹏-1.jpg",
        "name":"吕琨鹏",
        "needtip":2
    },
    {
        "src":"images/tab-1/吕琨鹏-2.jpg",
        "name":"吕琨鹏",
        "needtip":2
    },
    {
        "src":"images/tab-1/周贵公-1.jpg",
        "name":"周贵公",
        "needtip":2
    },
    {
        "src":"images/tab-1/周贵公-2.jpg",
        "name":"周贵公",
        "needtip":2
    },
    {
        "src":"images/tab-1/姜志鹏.jpg",
        "name":"姜志鹏",
        "needtip":2
    },
    {
        "src":"images/tab-1/姜文覃.jpg",
        "name":"姜文覃",
        "needtip":2
    },
    {
        "src":"images/tab-1/姜钰源.jpg",
        "name":"姜钰源",
        "needtip":2
    },
    {
        "src":"images/tab-1/孟昭文.jpg",
        "name":"孟昭文",
        "needtip":2
    },
    {
        "src":"images/tab-1/宠定全.jpg",
        "name":"宠定全",
        "needtip":2
    },
    {
        "src":"images/tab-1/宫少军.jpg",
        "name":"宫少军",
        "needtip":1
    },
    {
        "src":"images/tab-1/宫振学.jpg",
        "name":"宫振学",
        "needtip":2
    },
    {
        "src":"images/tab-1/宫振学-2.jpg",
        "name":"宫振学",
        "needtip":2
    },
    {
        "src":"images/tab-1/宫振学-3.jpg",
        "name":"宫振学",
        "needtip":2
    },
    {
        "src":"images/tab-1/宫振学-4.jpg",
        "name":"宫振学",
        "needtip":2
    },
    {
        "src":"images/tab-1/尚勇.jpg",
        "name":"尚勇",
        "needtip":2
    },
    {
        "src":"images/tab-1/崔显芹.jpg",
        "name":"崔显芹",
        "needtip":2
    },
    {
        "src":"images/tab-1/崔显霞.jpg",
        "name":"崔显霞",
        "needtip":2
    },
    {
        "src":"images/tab-1/常澄.jpg",
        "name":"常澄",
        "needtip":2
    },
    {
        "src":"images/tab-1/廖玉华-1.jpg",
        "name":"廖玉华",
        "needtip":2
    },
    {
        "src":"images/tab-1/廖玉华-2.jpg",
        "name":"廖玉华",
        "needtip":2
    },
    {
        "src":"images/tab-1/张子炎.jpg",
        "name":"张子炎",
        "needtip":2
    },
    {
        "src":"images/tab-1/张海涛联-1.jpg",
        "name":"张海涛",
        "needtip":2
    },
    {
        "src":"images/tab-1/张海涛联-2.jpg",
        "name":"张海涛",
        "needtip":2
    },
    {
        "src":"images/tab-1/张盛.jpg",
        "name":"张盛",
        "needtip":2
    },
    {
        "src":"images/tab-1/张龙.jpg",
        "name":"张龙",
        "needtip":2
    },
    {
        "src":"images/tab-1/徐剑霞.jpg",
        "name":"徐剑霞",
        "needtip":2
    },
    // {
    //     "src":"images/tab-1/徐艺.jpg",
    //     "name":"徐艺",
    //     "needtip":2
    // },
    {
        "src":"images/tab-1/方典云.jpg",
        "name":"方典云",
        "needtip":2
    },
    {
        "src":"images/tab-1/李升海.jpg",
        "name":"李升海",
        "needtip":2
    },
    {
        "src":"images/tab-1/李德香.jpg",
        "name":"李德香",
        "needtip":2
    },
    {
        "src":"images/tab-1/李柔伟.jpg",
        "name":"李柔伟",
        "needtip":2
    },
    {
        "src":"images/tab-1/李洪文.jpg",
        "name":"李洪文",
        "needtip":2
    },
    {
        "src":"images/tab-1/李美芹.jpg",
        "name":"李美芹",
        "needtip":2
    },
    {
        "src":"images/tab-1/李良杰联-1.jpg",
        "name":"李良杰",
        "needtip":2
    },
    {
        "src":"images/tab-1/李良杰联-2.jpg",
        "name":"李良杰",
        "needtip":2
    },
    {
        "src":"images/tab-1/李钧.jpg",
        "name":"李钧",
        "needtip":2
    },
    {
        "src":"images/tab-1/杨升林.jpg",
        "name":"杨升林",
        "needtip":2
    },
    {
        "src":"images/tab-1/杨达.jpg",
        "name":"杨达",
        "needtip":2
    },
    {
        "src":"images/tab-1/潘由之.jpg",
        "name":"潘由之",
        "needtip":2
    },
    {
        "src":"images/tab-1/王保鹏.jpg",
        "name":"王保鹏",
        "needtip":2
    },
    {
        "src":"images/tab-1/王响明.jpg",
        "name":"王响明",
        "needtip":2
    },
    {
        "src":"images/tab-1/王廷福.jpg",
        "name":"王廷福",
        "needtip":2
    },
    {
        "src":"images/tab-1/王海明-1.jpg",
        "name":"王海明",
        "needtip":2
    },
    {
        "src":"images/tab-1/王海明-2.jpg",
        "name":"王海明",
        "needtip":2
    },
    {
        "src":"images/tab-1/王顺昌.jpg",
        "name":"王顺昌",
        "needtip":2
    },
    {
        "src":"images/tab-1/石洪钧-1.jpg",
        "name":"石洪钧",
        "needtip":2
    },
    {
        "src":"images/tab-1/石洪钧-2.jpg",
        "name":"石洪钧",
        "needtip":2
    },
    {
        "src":"images/tab-1/綦升超.jpg",
        "name":"綦升超",
        "needtip":2
    },
    {
        "src":"images/tab-1/胡有娟.jpg",
        "name":"胡有娟",
        "needtip":2
    },
    {
        "src":"images/tab-1/辛汉明.jpg",
        "name":"辛汉明",
        "needtip":2
    },
    {
        "src":"images/tab-1/侯淑贞-2.jpg",
        "name":"侯淑贞",
        "needtip":2
    },
    {
        "src":"images/tab-1/钟爱珍-1.jpg",
        "name":"钟爱珍",
        "needtip":2
    },
    {
        "src":"images/tab-1/钟爱珍-2.jpg",
        "name":"钟爱珍",
        "needtip":2
    },
    {
        "src":"images/tab-1/陈燕-1.jpg",
        "name":"陈燕",
        "needtip":2
    },
    {
        "src":"images/tab-1/陈燕-2.jpg",
        "name":"陈燕",
        "needtip":2
    },
    {
        "src":"images/tab-1/韩尧先.jpg",
        "name":"韩尧先",
        "needtip":2
    },
    {
        "src":"images/tab-1/韩瑞健.jpg",
        "name":"韩瑞健",
        "needtip":2
    },
    {
        "src":"images/tab-1/高专.jpg",
        "name":"高专",
        "needtip":2
    },
    {
        "src":"images/tab-1/高如林.jpg",
        "name":"高如林",
        "needtip":2
    },
    {
        "src":"images/tab-1/高愈增.jpg",
        "name":"高愈增",
        "needtip":2
    },
    {
        "src":"images/tab-1/龚学文.jpg",
        "name":"龚学文",
        "needtip":2
    }
];

var dataTab2 = [
    {
        "src":"images/tab-2/1-高东方-1.jpg",
        "name":"高东方",
        "needtip":2
    },
    {
        "src":"images/tab-2/1-高东方-2.jpg",
        "name":"高东方",
        "needtip":2
    },
    {
        "src":"images/tab-2/10-高运达.jpg",
        "name":"高运达",
        "needtip":2
    },
    {
        "src":"images/tab-2/10-高运达-2.jpg",
        "name":"高运达",
        "needtip":1
    },
    {
        "src":"images/tab-2/10-高运达-3.jpg",
        "name":"高运达",
        "needtip":2
    },
    {
        "src":"images/tab-2/11-张建波.jpg",
        "name":"张建波",
        "needtip":2
    },
    {
        "src":"images/tab-2/11-张建波-2.jpg",
        "name":"张建波",
        "needtip":2
    },
    {
        "src":"images/tab-2/12-周红 书法-1.jpg",
        "name":"周红",
        "needtip":2
    },
    {
        "src":"images/tab-2/12-周红书法.jpg",
        "name":"周红",
        "needtip":2
    },
    {
        "src":"images/tab-2/12-周红山水.jpg",
        "name":"周红",
        "needtip":2
    },
    {
        "src":"images/tab-2/13-许晓斌-1.jpg",
        "name":"许晓斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/13-许晓斌-2.jpg",
        "name":"许晓斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/14-高振洪.jpg",
        "name":"高振洪",
        "needtip":2
    },
    {
        "src":"images/tab-2/14-高振洪联-1.jpg",
        "name":"高振洪",
        "needtip":2
    },
    {
        "src":"images/tab-2/14-高振洪联-2.jpg",
        "name":"高振洪",
        "needtip":2
    },
    {
        "src":"images/tab-2/15-谢添.jpg",
        "name":"谢添",
        "needtip":1
    },
    {
        "src":"images/tab-2/16-王莹1.jpg",
        "name":"王莹",
        "needtip":2
    },
    {
        "src":"images/tab-2/16-王莹2.jpg",
        "name":"王莹",
        "needtip":2
    },
    {
        "src":"images/tab-2/17-徐辉.jpg",
        "name":"徐辉",
        "needtip":2
    },
    {
        "src":"images/tab-2/17-徐辉2.jpg",
        "name":"徐辉",
        "needtip":2
    },
    {
        "src":"images/tab-2/18-郭斌-3.jpg",
        "name":"郭斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/18-郭斌-4.jpg",
        "name":"郭斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/18-郭斌对联-1.jpg",
        "name":"郭斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/18-郭斌对联-2.jpg",
        "name":"郭斌",
        "needtip":2
    },
    {
        "src":"images/tab-2/19-修相科.jpg",
        "name":"修相科",
        "needtip":2
    },
    {
        "src":"images/tab-2/2-张凤祥-1.jpg",
        "name":"张凤祥",
        "needtip":2
    },
    {
        "src":"images/tab-2/2-张凤祥-2.jpg",
        "name":"张凤祥",
        "needtip":2
    },
    {
        "src":"images/tab-2/20王旭艳.jpg",
        "name":"王旭艳",
        "needtip":2
    },
    {
        "src":"images/tab-2/20-王旭艳-2.JPG",
        "name":"王旭艳",
        "needtip":2
    },
    {
        "src":"images/tab-2/21-代文顺.jpg",
        "name":"代文顺",
        "needtip":2
    },
    {
        "src":"images/tab-2/21-代文顺-2.jpg",
        "name":"代文顺",
        "needtip":2
    },
    {
        "src":"images/tab-2/22-王宝江.jpg",
        "name":"王宝江",
        "needtip":2
    },
    {
        "src":"images/tab-2/22-王宝江-2.jpg",
        "name":"王宝江",
        "needtip":2
    },
    {
        "src":"images/tab-2/23-任业涌.jpg",
        "name":"任业涌",
        "needtip":2
    },
    {
        "src":"images/tab-2/24-徐艺.jpg",
        "name":"徐艺",
        "needtip":2
    },
    {
        "src":"images/tab-2/24-谢永健.jpg",
        "name":"谢永健",
        "needtip":2
    },
    {
        "src":"images/tab-2/3-孙云层-1.jpg",
        "name":"孙云层",
        "needtip":2
    },
    {
        "src":"images/tab-2/3-孙云层-2.jpg",
        "name":"孙云层",
        "needtip":2
    },
    {
        "src":"images/tab-2/4-张志钢-1.jpg",
        "name":"张志钢",
        "needtip":2
    },
    {
        "src":"images/tab-2/4-张志钢-2.jpg",
        "name":"张志钢",
        "needtip":2
    },
    {
        "src":"images/tab-2/4-张志钢-3.jpg",
        "name":"张志钢",
        "needtip":1
    },
    {
        "src":"images/tab-2/4-张志钢-4.jpg",
        "name":"张志钢",
        "needtip":1
    },
    {
        "src":"images/tab-2/5-马斗进.jpg",
        "name":"马斗进",
        "needtip":2
    },
    {
        "src":"images/tab-2/5-马斗进-楹联-1.jpg",
        "name":"马斗进",
        "needtip":2
    },
    {
        "src":"images/tab-2/5-马斗进-楹联-2.jpg",
        "name":"马斗进",
        "needtip":2
    },
    {
        "src":"images/tab-2/6-杨传坤-1.jpg",
        "name":"杨传坤",
        "needtip":2
    },
    {
        "src":"images/tab-2/6-杨传坤-2.jpg",
        "name":"杨传坤",
        "needtip":2
    },
    {
        "src":"images/tab-2/7-朱文松.jpg",
        "name":"朱文松",
        "needtip":2
    },
    {
        "src":"images/tab-2/7-朱文松-2.jpg",
        "name":"朱文松",
        "needtip":2
    },
    {
        "src":"images/tab-2/8-张学正-1.jpg",
        "name":"张学正",
        "needtip":2
    },
    {
        "src":"images/tab-2/8-张学正-2.jpg",
        "name":"张学正",
        "needtip":2
    },
    {
        "src":"images/tab-2/9-高杰-1.jpg",
        "name":"高杰",
        "needtip":2
    },
    {
        "src":"images/tab-2/9-高杰-2.jpg",
        "name":"高杰",
        "needtip":2
    }
];

dataTab1 = dataTab1.sort(function(str1, str2) {
    return str1.name.localeCompare(str2.name, 'zh');
});


dataTab2 = dataTab2.sort(function(item1, item2) {
    var pure1 = item1.src.replace('images/tab-2/', '');
    var pure2 = item2.src.replace('images/tab-2/', '');
    var pattern = /[0-9]+/;
    var v1 = parseInt(pattern.exec(pure1)[0]);
    var v2 = parseInt(pattern.exec(pure2)[0]);
    // console.log(pure2)
    // console.log(label2)
    // console.log('-------------')
    if (v1 < v2) {
        return -1;
    } else if (v1 > v2) {
        return 1;
    } else {
        return 0;
    }
});